name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test - ${{ matrix.os.name }} ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
          - name: macOS
            runs-on: macos-latest
          - name: Windows
            runs-on: windows-latest
        python:
          - name: CPython 2.7
            tox: py27
            action: 2.7
          - name: CPython 3.5
            tox: py35
            action: 3.5
          - name: CPython 3.6
            tox: py36
            action: 3.6
          - name: CPython 3.7
            tox: py37
            action: 3.7
          - name: CPython 3.8
            tox: py38
            action: 3.8
          - name: CPython 3.9
            tox: py39
            action: 3.9
          - name: PyPy 2
            tox: pypy2
            action: pypy2
          - name: PyPy 3
            tox: pypy3
            action: pypy3
        exclude:
          # Twisted and thus trial do not work on Windows with CPython 3.9.
          # This will be fixed with the next release.
          # https://twistedmatrix.com/trac/ticket/10027
          - python:
              tox: py39
            os:
              name: Windows

    steps:
    - uses: actions/checkout@v2

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.action }}

    - uses: twisted/python-info-action@v1.0.1

    - name: Install dependencies
      run: python -m pip install --upgrade pip tox codecov

    - name: Test
      run: tox -c tox.ini -e ${{ matrix.python.tox }}-tests

    - name: Codecov
      run: |
        codecov -n "GitHub Actions - Test - ${{ matrix.os.name }} ${{ matrix.python.name }}"

  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        # Using second most recent minor release for whatever little
        # increase in stability over using the latest minor.
        python-version: 3.8

    - uses: twisted/python-info-action@v1.0.1

    - name: Install dependencies
      id: last_step_before_checks
      run: python -m pip install --upgrade pip tox

    - name: Lint
      if: ${{ steps.last_step_before_checks.outcome }} == "success"
      run: tox -c tox.ini -e flake8

    - name: Manifest
      if: ${{ steps.last_step_before_checks.outcome }} == "success"
      run: tox -c tox.ini -e check-manifest

    - name: Newsfragment
      if: ${{ steps.last_step_before_checks.outcome }} == "success"
      run: tox -c tox.ini -e check-newsfragment

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - test
      - check
    steps:
      - name: This
        shell: python
        run: import this
