name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.task.name}} - ${{ matrix.os.name }} ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
          - name: macOS
            runs-on: macos-latest
          - name: Windows
            runs-on: windows-latest
        python:
          - name: CPython 2.7
            tox: py27
            action: 2.7
            tox_major: 3
          - name: CPython 3.5
            tox: py35
            action: 3.5
            tox_major: 3
          - name: CPython 3.6
            tox: py36
            action: 3.6
            tox_major: 4
          - name: CPython 3.7
            tox: py37
            action: 3.7
            tox_major: 4
          - name: CPython 3.8
            tox: py38
            action: 3.8
            tox_major: 4
          - name: CPython 3.9
            tox: py39
            action: 3.9
            tox_major: 4
          - name: PyPy 2.7
            tox: pypy27
            action: pypy-2.7
            tox_major: 4
          - name: PyPy 3.6
            tox: pypy36
            action: pypy-3.6
            tox_major: 4
          - name: PyPy 3.7
            tox: pypy37
            action: pypy-3.7
            tox_major: 4
        tox:
          # There is only a single value here so the matrix size is not
          # increased.  This does give a nice way to define variables
          # though.
          - 3:
              command: tox
              version_specifier: tox~=3.0
            4:
              command: tox4
              version_specifier: tox~=4.0a5
        task:
          - name: Test
            tox: tests
        exclude:
          # Twisted and thus trial do not work on Windows with CPython 3.9.
          # This will be fixed with the next release.
          # https://twistedmatrix.com/trac/ticket/10027
          - python:
              tox: py39
            os:
              name: Windows

    steps:
    - uses: actions/checkout@v2

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.action }}

    - uses: twisted/python-info-action@v1.0.1

    - name: Install dependencies
      run: python -m pip install --upgrade pip codecov ${{ matrix.tox[matrix.python.tox_major].version_specifier }}

    - name: Test
      run: ${{ matrix.tox[matrix.python.tox_major].command }} -c tox.ini -e ${{ matrix.python.tox }}-tests

    - name: Codecov
      run: |
        codecov -n "GitHub Actions - ${{ matrix.task.name}} - ${{ matrix.os.name }} ${{ matrix.python.name }}"

  check:
    name: ${{ matrix.task.name}} - ${{ matrix.python.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          # Using second most recent minor release for whatever little
          # increase in stability over using the latest minor.
          - name: CPython 3.8
            tox: py38
            action: 3.8
            tox_major: 4
        tox:
          # There is only a single value here so the matrix size is not
          # increased.  This does give a nice way to define variables
          # though.
          - 3:
              command: tox
              version_specifier: tox~=3.0
            4:
              command: tox4
              version_specifier: tox~=4.0a5
        task:
          - name: Flake8
            tox: flake8
          - name: Check Manifest
            tox: check-manifest
          - name: Check Newsfragment
            tox: check-newsfragment

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.action }}

    - uses: twisted/python-info-action@v1.0.1

    - name: Install dependencies
      run: python -m pip install --upgrade pip ${{ matrix.tox[matrix.python.tox_major].version_specifier }}

    - name: Check
      run: ${{ matrix.tox[matrix.python.tox_major].command }} -c tox.ini -e ${{ matrix.task.tox }}

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - test
      - check
    steps:
      - name: This
        shell: python
        run: import this
